spring:jmx:enabled: false

spring:
  datasource:
    url: "jdbc:mysql://localhost:3305/fastsns"
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true